import random

german_words = [
    {"German": "der", "English": "the (masculine)"},
    {"German": "die", "English": "the (feminine)"},
    {"German": "und", "English": "and"},
    {"German": "in", "English": "in"},
    {"German": "zu", "English": "to"},
    {"German": "den", "English": "the (dative masculine, plural)"},
    {"German": "das", "English": "the (neuter)"},
    {"German": "von", "English": "from"},
    {"German": "mit", "English": "with"},
    {"German": "sich", "English": "oneself"},
    {"German": "des", "English": "of the (genitive masculine)"},
    {"German": "auf", "English": "on"},
    {"German": "für", "English": "for"},
    {"German": "ist", "English": "is"},
    {"German": "im", "English": "in the (contraction of 'in dem')"},
    {"German": "dem", "English": "the (dative neuter)"},
    {"German": "nicht", "English": "not"},
    {"German": "ein", "English": "a, an"},
    {"German": "Die", "English": "the (plural)"},
    {"German": "eine", "English": "a, an (feminine)"},
    {"German": "als", "English": "as"},
    {"German": "auch", "English": "also, too"},
    {"German": "es", "English": "it"},
    {"German": "an", "English": "at"},
    {"German": "werden", "English": "to become"},
    {"German": "aus", "English": "out of, from"},
    {"German": "er", "English": "he"},
    {"German": "hat", "English": "has"},
    {"German": "nach", "English": "after, to"},
    {"German": "wird", "English": "will, shall"},
    {"German": "sind", "English": "are"},
    {"German": "was", "English": "what"},
    {"German": "soll", "English": "should"},
    {"German": "haben", "English": "to have"},
    {"German": "nur", "English": "only"},
    {"German": "war", "English": "was"},
    {"German": "sein", "English": "to be"},
    {"German": "wenn", "English": "if, when"},
    {"German": "einer", "English": "one (feminine)"},
    {"German": "hier", "English": "here"},
    {"German": "wie", "English": "how, like, as"},
    {"German": "bei", "English": "at, near, with, by"},
    {"German": "oder", "English": "or"},
    {"German": "um", "English": "around, at, in order to"},
    {"German": "nach", "English": "to, towards, after"},
    {"German": "aber", "English": "but"},
    {"German": "vor", "English": "in front of, before"},
    {"German": "durch", "English": "through, by"},
    {"German": "man", "English": "one, you, they, people"},
    {"German": "noch", "English": "still, yet"},
    {"German": "wie", "English": "how, what, as"},
    {"German": "mein", "English": "my"},
    {"German": "kein", "English": "no, none, not any"},
    {"German": "uns", "English": "us"},
    {"German": "sich", "English": "themselves"},
    {"German": "ihr", "English": "her, their, you (plural)"},
    {"German": "zum", "English": "to the (contraction of 'zu dem')"},
    {"German": "über", "English": "over, about, above"},
    {"German": "so", "English": "so"},
    {"German": "bis", "English": "until"},
    {"German": "doch", "English": "yet, still, nevertheless"},
    {"German": "ihn", "English": "him"},
    {"German": "unter", "English": "under, below, among"},
    {"German": "hatte", "English": "had"},
    {"German": "können", "English": "can, to be able to"},
    {"German": "seine", "English": "his"},
    {"German": "gegen", "English": "against"},
    {"German": "ihn", "English": "him, it"},
    {"German": "oder", "English": "or"},
    {"German": "kein", "English": "none, not any"},
    {"German": "dass", "English": "that"},
    {"German": "mehr", "English": "more, anymore"},
    {"German": "selbst", "English": "self, himself, herself"},
    {"German": "sehr", "English": "very"},
    {"German": "schon", "English": "already, yet, still"},
    {"German": "hier", "English": "here"},
    {"German": "bis", "English": "until"},
    {"German": "werde", "English": "will, shall"},
    {"German": "dann", "English": "then"},
    {"German": "uns", "English": "us"},
    {"German": "ihr", "English": "her, their, you (plural)"},
    {"German": "also", "English": "so, therefore, consequently"},
    {"German": "dieser", "English": "this, that"},
    {"German": "ihm", "English": "him, to him"},
    {"German": "einen", "English": "one (masculine)"},
    {"German": "mich", "English": "me"},
    {"German": "mir", "English": "to me"},
    {"German": "wieder", "English": "again"},
    {"German": "nur", "English": "only, just"},
    {"German": "würde", "English": "would"},
    {"German": "sein", "English": "his"},
    {"German": "etwas", "English": "something, somewhat, anything"},
    {"German": "diese", "English": "this (feminine)"},
    {"German": "ihn", "English": "him, it"},
    {"German": "uns", "English": "us"},
    {"German": "ihnen", "English": "them, to them"},
    {"German": "meine", "English": "my (feminine)"},
    {"German": "wird", "English": "will, shall (future tense)"},
    {"German": "ihr", "English": "her, their, you (plural)"},
    {"German": "uns", "English": "us"},
    {"German": "einem", "English": "one (masculine, dative)"},
    {"German": "eine", "English": "a, an (feminine)"},
    {"German": "haben", "English": "to have (infinitive)"},
    {"German": "dieses", "English": "this (neuter)"},
    {"German": "seinen", "English": "his (masculine)"},
    {"German": "durch", "English": "through, by"},
    {"German": "mehr", "English": "more"},
    {"German": "so", "English": "so"},
    {"German": "viel", "English": "much, many"},
    {"German": "nun", "English": "now"},
    {"German": "wurde", "English": "was (past tense of 'werden')"},
    {"German": "muss", "English": "must, have to"},
    {"German": "ohne", "English": "without"},
    {"German": "können", "English": "can, to be able to"},
    {"German": "selbst", "English": "self, himself, herself"},
    {"German": "schon", "English": "already, yet, still"},
    {"German": "hier", "English": "here"},
    {"German": "bis", "English": "until"},
    {"German": "wieder", "English": "again"},
    {"German": "gegen", "English": "against"},
    {"German": "unter", "English": "under, below, among"},
    {"German": "dort", "English": "there"},
    {"German": "vor", "English": "before, in front of"},
    {"German": "werde", "English": "will, shall (future tense of 'werden')"},
    {"German": "seine", "English": "his"},
    {"German": "ihm", "English": "him, to him"},
    {"German": "also", "English": "so, therefore, consequently"},
    {"German": "dieser", "English": "this (masculine)"},
    {"German": "einen", "English": "a, an (masculine)"},
    {"German": "mich", "English": "me"},
    {"German": "mir", "English": "to me"},
    {"German": "etwas", "English": "something, somewhat, anything"},
    {"German": "diese", "English": "this (feminine, plural)"},
    {"German": "werden", "English": "to become, will"},
    {"German": "ihren", "English": "their (feminine)"},
    {"German": "machen", "English": "to do, to make"},
    {"German": "doch", "English": "yet, still, nevertheless"},
    {"German": "keine", "English": "none, not any (feminine)"},
    {"German": "wissen", "English": "to know"},
    {"German": "wo", "English": "where"},
    {"German": "denn", "English": "then, because"},
    {"German": "seinem", "English": "his (dative masculine)"},
    {"German": "Zeit", "English": "time"},
    {"German": "nehmen", "English": "to take"},
    {"German": "jetzt", "English": "now"},
    {"German": "wohl", "English": "probably, well"},
    {"German": "unter", "English": "under"},
    {"German": "zurück", "English": "back"},
    {"German": "geben", "English": "to give"},
    {"German": "kommen", "English": "to come"},
    {"German": "sollen", "English": "should, supposed to"},
    {"German": "ja", "English": "yes, indeed"},
    {"German": "denn", "English": "because, then"},
    {"German": "sehen", "English": "to see"},
    {"German": "lassen", "English": "to let, to allow"},
    {"German": "sagen", "English": "to say, to tell"},
    {"German": "seiner", "English": "his (genitive masculine)"},
    {"German": "jahr", "English": "year"},
    {"German": "immer", "English": "always"},
    {"German": "ihr", "English": "her, their, you (plural)"},
    {"German": "Millionen", "English": "millions"},
    {"German": "gut", "English": "good"},
    {"German": "Tag", "English": "day"},
    {"German": "diese", "English": "this (feminine)"},
    {"German": "sagt", "English": "says"},
    {"German": "muß", "English": "must, have to"},
    {"German": "gar", "English": "even"},
    {"German": "mal", "English": "time"},
    {"German": "dazu", "English": "to it, for it, about it"},
    {"German": "zwei", "English": "two"},
    {"German": "drei", "English": "three"},
    {"German": "jeder", "English": "each, every"},
    {"German": "dort", "English": "there"},
    {"German": "kann", "English": "can, is able to"},
    {"German": "solche", "English": "such"},
    {"German": "ganz", "English": "whole, entire, all"},
    {"German": "während", "English": "while, during"},
    {"German": "nun", "English": "now"},
    {"German": "sagte", "English": "said"},
    {"German": "denn", "English": "because"},
    {"German": "etwa", "English": "approximately, about"},
    {"German": "sollte", "English": "should, ought to"},
    {"German": "keine", "English": "none, not any"},
    {"German": "ja", "English": "yes, indeed"},
    {"German": "jemand", "English": "someone, somebody"},
    {"German": "werden", "English": "will, shall"},
    {"German": "weil", "English": "because"},
    {"German": "könnte", "English": "could, might"}
]


def quiz_user(german_words):
    random.shuffle(german_words)
    score = 0

    for word in german_words:
        print(f"What is the English Translation of {word["German"]}""?")
        user_answer = input("Your answer: ").strip().lower()
        correct_answer = word["English"].lower()

        if user_answer == correct_answer:
            print("Correct!!\n")
            score += 1
        else:
            print(f"Not so right! Correct answer is {word["English"]}""\n")

    print(f"Quiz Complete! Your Score: {score}/{len(german_words)}")


def main():
    print("Welcome to the Language Learning Flashcard App")
    input("Presws Enter to Start quiz...")
    quiz_user(german_words)


if __name__ == "__main__":
    main()
